//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public string Num { get; set; }
        public string adress { get; set; }
        public string vid { get; set; }
        public Nullable<int> rast { get; set; }
    }
}
